# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-11 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atik',
            name='end_date',
            field=models.DateField(null=True, verbose_name=['%Y-%m-%d %H:%M:%S']),
        ),
    ]
