# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-12 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_blog', '0002_atik_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atik',
            name='foto_atik',
            field=models.ImageField(blank=True, upload_to='atik/img_atik/', verbose_name='img'),
        ),
    ]
