# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-16 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_blog', '0003_auto_20160512_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_name', models.CharField(default='mak machin nan', max_length=100)),
                ('auto_model', models.CharField(default='model machin nan', max_length=100)),
                ('transmission', models.CharField(choices=[('automatique', '1'), ('shift', '2')], default=('shift', '2'), max_length=255)),
                ('color', models.CharField(default='kouleu machin nan', max_length=50)),
                ('slug', models.SlugField(default='slug', max_length=255, unique=True)),
                ('deskripsyon', models.TextField(default='Deskripsyon pwodui a')),
                ('specs', models.CharField(default='Kek lot detay sou pwodui a', max_length=255)),
                ('uploaded', models.DateField(auto_now_add=True, verbose_name='Pwodui sa online depi')),
                ('published', models.BooleanField(default=True)),
                ('seller', models.CharField(default='Moun kap vann nan', max_length=75)),
                ('kontak', models.CharField(default='Nimewo telefon ou', max_length=11)),
                ('pri', models.IntegerField(default='Pri pwodui a an HTG')),
                ('end_date', models.DateField(null=True, verbose_name=['%Y-%m-%d %H:%M:%S'])),
                ('foto_machin', models.ImageField(blank=True, upload_to='foto_machin/', verbose_name='img')),
            ],
            options={
                'ordering': ['uploaded'],
            },
        ),
        migrations.AlterField(
            model_name='atik',
            name='foto_atik',
            field=models.ImageField(blank=True, upload_to='', verbose_name='img'),
        ),
    ]
